version: '2.3'
services:
  message_server:
    container_name: cosmos-container
    image: dshulakov/cosmos-app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRE_LENGTH=${JWT_ACCESS_TOKEN_EXPIRE_LENGTH}
      - JWT_REFRESH_TOKEN_EXPIRE_LENGTH=${JWT_REFRESH_TOKEN_EXPIRE_LENGTH}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - BASE_URL=${BASE_URL}
    depends_on:
      - postgresql
  postgresql:
    container_name: postresql-container
    image: postgres:14.3
    volumes:
      - cosmos-app-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=cosmos_db
volumes:
  cosmos-app-db: